### ISSUE TITLE
Exception thrown when sending updates for multiple networks

### ISSUE THREAD

**Issue by AndisGrossteins** [songposter/plugin-radiodj#1]
As [discussed on RadioDJ forums](http://www.radiodj.ro/community/index.php?topic=5920.msg48516#msg48516), an exception is thrown and RadioDJ UI is locked when the plugin sends updates.
### The exception

`System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&> System.Threading.ThreadStateException: Thread is running or terminated; it cannot restart.`
### The cause

Same thread cannot be reused in a foreach loop. A new thread has to be created and started for each update.
Here is the line where it goes wrong:
https://github.com/songposter/plugin-radiodj/blob/master/Plugin_SongPoster/WebRequester.cs#L27
### The solution

Move new thread object creation inside the foreach loop.

BTW, setting `Content-Type` header to `application/x-www-form-urlencoded` for GET requests is not useful.

**Comment by mastacheata** [comment]
Thanks for the hint.
After you mentioned it, it's so obvious why this is can't work.

Tried your fix in a separate branch and it seems to work really well.
For the main branch, I diverted to a different solution that works without creating additional threads by hand altogether and comes closer to the work mode I'm used to as a web developer.

I'm now using an async method to send the request. I haven't been doing any proper error handling anyways and can't see what kind of error handling to implement at all.

Yeah, setting the content-type is needless here. Missed that part from the web example I copied.
