### ISSUE TITLE
Updates fail because password is not urlencoded

### ISSUE THREAD

**Issue by AndisGrossteins** [songposter/plugin-radiodj#2]
My password is automatically generated and contains hash character `#`, which truncates the url on web server.
For example, if password is `Allm0st#secure%pa$$word?`, after the URL is parsed by server the request looks like this:

```
GET /send-post/twitter/0/4242/Allm0st HTTP/1.1
```

I tested it by proxying all requests to my local Apache 2.4 but it should not be any different on other servers.

The password field has to be urlencoded.

**Comment by mastacheata** [comment]
Fixed in 11fae53
